### ISSUE TITLE
connect many device and scrollong text

### ISSUE THREAD

**Issue by Jimmy76gr** [Seeed-Studio/Grove_LED_Matrix_Driver_HT16K33#1]
hello how i can add many device and scroll text with out spaces? for exaple 1231 or 9119 
the device shooud have to set different i2c adress?

**Comment by ackPeng** [comment]
Yes, different devices on the IIC bus should have different addresses; can you provide more information about "scrolling text without leaving spaces"?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
